### PR TITLE
Modify tests and add Jenkins support

### PR DESCRIPTION
**Pull request by nanliu**
* use container for faster travis test
* change unit test to small
* add ability to filter tests
* add ability to increase debug level

### CODE REVIEW

**Comment by nanliu** [comment]
This is to verify job in jjb for jenkins. Do not merge.

**Comment by candysmurf** [comment]
@nanliu , would you please rebase your change? thanks

**Comment by candysmurf** [comment]
👍 , Awesome enhancements @nanliu.   LGTM.

**Comment by thomastaylor312** [comment]
Thanks for doing this @nanliu, this is awesome!

**Comment by nanliu** [comment]
please test this

**Comment by nanliu** [comment]
please test this

**Comment by nanliu** [comment]
Please test this

**Pull request merged**
